# Generated by Django 4.2 on 2023-04-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign_review',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
