# Generated by Django 4.2 on 2023-04-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_appkeyword_screenshot_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_screenshot',
            name='ratings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
